In [1]:
import torch

In [2]:
one_d = torch.arange(2, 7)

In [3]:
one_d

tensor([2, 3, 4, 5, 6])

In [4]:
one_d = torch.arange(0,9)

In [5]:
two_d = one_d.view(3,3)

In [6]:
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
two_d.dim()

2

In [9]:
two_d[0, 0]

tensor(0)

In [10]:
two_d[1, 2]

tensor(5)

In [11]:
two_d[2,1]

tensor(7)

In [12]:
x = torch.arange(0, 18).view(2,3,3)

In [13]:
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [14]:
x = torch.arange(0,18).view(3,3,2)

In [15]:
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [16]:
x = torch.arange(0,36).view(3,3,4)

In [17]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]])