In [18]:
import torch
import numpy as np

In [2]:
v = torch.tensor([1,2,3])
print(v)

tensor([1, 2, 3])


In [3]:
print(v.dtype)

torch.int64


In [4]:
print(v[0])

tensor(1)


In [5]:
print(v[1])

tensor(2)


In [6]:
v = torch.tensor([1,2,3,4,5,6])

In [7]:
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [8]:
print(v[1:4])

tensor([2, 3, 4])


In [9]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [10]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.dtype)

torch.float32


In [11]:
print(f.size())

torch.Size([6])


In [12]:
v.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [13]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
v.view(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
a = np.array([1,2,3,4,5])

In [20]:
tensor_cnv = torch.from_numpy(a)

In [21]:
print(tensor_cnv)

tensor([1, 2, 3, 4, 5])


In [22]:
print(tensor_cnv.dtype)

torch.int64


In [23]:
numpy_cnv = tensor_cnv.numpy()

In [24]:
print(numpy_cnv)

[1 2 3 4 5]
